version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: pancakes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bazepodataka
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pancakes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bazepodataka

  frontend:
    build:
      context: ./pancakes_front
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - app
volumes:
  pgdata: