
spring:
    application:
        name: pancake
    datasource:
        url: jdbc:postgresql://postgres:5432/pancakes
        username: postgres
        password: bazepodataka

    flyway:
        enabled: true

    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

server:
    servlet:
        context-path: /
